"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Check, ChartLineUp, Lightning, ShieldCheck, Sparkle, TrendUp } from "@phosphor-icons/react";
import { Wordmark } from "@/components/brand/wordmark";

const rise = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };

export function LandingPageContent() {
  return <main className="min-h-screen overflow-hidden bg-[#090b10] text-[#f7f6f3] selection:bg-[#b5ff6d] selection:text-[#10120d]">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[780px] bg-[radial-gradient(ellipse_at_50%_-10%,rgba(170,255,85,.16),transparent_48%),radial-gradient(ellipse_at_85%_30%,rgba(87,117,255,.12),transparent_35%)]" />
    <div className="relative mx-auto max-w-[1240px] px-5 sm:px-8"><Nav /><Hero /><LogoStrip /><SignalSection /><RecoveryFlow /><Closing /><Footer /></div>
  </main>;
}

function Nav() { return <nav className="flex h-[82px] items-center justify-between border-b border-white/[.10]"><Link href="/" aria-label="Undrop home"><Wordmark className="h-7 w-[120px] text-white" /></Link><div className="hidden items-center gap-8 text-sm text-white/55 md:flex"><a href="#product" className="transition hover:text-white">Product</a><a href="#how-it-works" className="transition hover:text-white">How it works</a><a href="#security" className="transition hover:text-white">Security</a></div><div className="flex items-center gap-4 text-sm font-medium"><Link href="/sign-in" className="hidden text-white/70 transition hover:text-white sm:block">Sign in</Link><Link href="/sign-up" className="rounded-full bg-[#b5ff6d] px-4 py-2.5 text-[#11130e] transition hover:bg-[#d1ff9f]">Get started <ArrowRight className="ml-1 inline-block" size={14} weight="bold" /></Link></div></nav>; }

function Hero() { return <section className="relative pb-20 pt-20 sm:pb-28 sm:pt-28"><motion.div initial="hidden" animate="show" transition={{ staggerChildren: .1 }} className="mx-auto max-w-[830px] text-center"><motion.div variants={rise} className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b5ff6d]/25 bg-[#b5ff6d]/[.08] px-3 py-1.5 text-xs font-medium text-[#c7ff91]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#b5ff6d]" />Built for teams on Razorpay</motion.div><motion.h1 variants={rise} className="font-display text-[clamp(3.2rem,8vw,6.6rem)] font-medium leading-[.91] tracking-[-.065em] text-white">Failed payments<br /><span className="text-[#b5ff6d]">don&apos;t have to stay failed.</span></motion.h1><motion.p variants={rise} className="mx-auto mt-7 max-w-[585px] text-base leading-7 text-white/60 sm:text-lg">Undrop notices revenue at risk, understands why it failed, and gives every customer the smartest possible path back to payment.</motion.p><motion.div variants={rise} className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/sign-up" className="rounded-full bg-[#b5ff6d] px-5 py-3 text-sm font-semibold text-[#11130e] transition hover:-translate-y-0.5 hover:bg-[#d1ff9f]">Start recovering revenue <ArrowRight className="ml-1 inline-block" size={16} weight="bold" /></Link><a href="#product" className="rounded-full border border-white/[.18] px-5 py-3 text-sm font-medium text-white/80 transition hover:border-white/40 hover:bg-white/[.04]">See how it works</a></motion.div></motion.div><motion.div initial={{ opacity: 0, y: 34, scale: .98 }} whileInView={{ opacity: 1, y: 0, scale: 1 }} viewport={{ once: true }} transition={{ duration: .8, delay: .25, ease: [0.16, 1, .3, 1] }} className="relative mx-auto mt-16 max-w-[1080px] rounded-[28px] border border-white/[.13] bg-[#10141b] p-2 shadow-[0_40px_90px_rgba(0,0,0,.48)]"><div className="absolute -inset-20 -z-10 bg-[#b5ff6d]/10 blur-[110px]" /><DashboardPreview /></motion.div></section>; }

function DashboardPreview() { return <div className="overflow-hidden rounded-[21px] border border-white/[.07] bg-[#0c0f14]"><div className="flex h-12 items-center justify-between border-b border-white/[.07] px-4 sm:px-5"><div className="flex gap-2"><span className="h-2 w-2 rounded-full bg-[#ff6e70]" /><span className="h-2 w-2 rounded-full bg-[#ffc86b]" /><span className="h-2 w-2 rounded-full bg-[#b5ff6d]" /></div><p className="font-mono text-[10px] text-white/35">LIVE RECOVERY CONSOLE</p><span className="w-10" /></div><div className="grid min-h-[420px] grid-cols-1 sm:grid-cols-[170px_1fr]"><aside className="hidden border-r border-white/[.07] p-4 sm:block"><p className="mb-7 text-xs font-semibold text-white">undrop</p>{["Overview", "Recoveries", "Signals", "Automations"].map((item, i) => <div key={item} className={`mb-1 rounded-lg px-3 py-2 text-xs ${i === 0 ? "bg-white/[.08] text-white" : "text-white/40"}`}>{item}</div>)}</aside><div className="p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs text-white/45">Good morning, Priya</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em] sm:text-2xl">Revenue, back on track.</h2></div><div className="hidden rounded-full bg-[#b5ff6d]/10 px-3 py-1.5 text-xs text-[#b5ff6d] sm:block">● Systems healthy</div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Recovered today" value="₹84,260" change="+18.2%" /><Metric label="At-risk revenue" value="₹1.42L" change="Watching" neutral /><Metric label="Recovery rate" value="31.8%" change="+5.4 pts" /></div><div className="mt-5 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><div className="flex justify-between"><p className="text-xs text-white/55">Recovery performance</p><p className="text-xs text-[#b5ff6d]">Last 7 days</p></div><div className="mt-5 flex h-28 items-end gap-2">{[34,42,38,67,50,74,92,70,86,100,78,92].map((h,i)=><motion.i key={i} initial={{ height: 0 }} whileInView={{ height: `${h}%` }} viewport={{ once:true }} transition={{ delay: .4+i*.035, duration:.45 }} className="block flex-1 rounded-t-sm bg-gradient-to-t from-[#6abe29] to-[#c7ff91]" />)}</div><div className="mt-3 flex justify-between text-[10px] text-white/30"><span>Mon</span><span>Wed</span><span>Fri</span><span>Today</span></div></div><div className="rounded-2xl border border-[#b5ff6d]/20 bg-[#b5ff6d]/[.055] p-4"><div className="flex items-center gap-2 text-[#c7ff91]"><Sparkle size={17} weight="fill" /><p className="text-xs font-medium">New signal</p></div><p className="mt-4 text-sm leading-5 text-white/85">UPI failures are elevated for HDFC customers.</p><p className="mt-2 text-xs leading-4 text-white/45">A recovery flow has been tuned and is now active.</p><button className="mt-4 text-xs font-medium text-[#c7ff91]">View signal →</button></div></div></div></div></div>; }

function Metric({label,value,change,neutral}:{label:string;value:string;change:string;neutral?:boolean}) { return <div className="rounded-xl border border-white/[.08] bg-white/[.025] p-3 sm:p-4"><p className="text-[10px] text-white/40">{label}</p><p className="mt-2 text-base font-medium tracking-[-.03em] sm:text-lg">{value}</p><p className={`mt-1 text-[10px] ${neutral ? "text-white/45" : "text-[#b5ff6d]"}`}>{change}</p></div>; }
function LogoStrip() { return <div className="border-y border-white/[.09] py-6 text-center"><p className="text-xs text-white/35">Designed for the teams who obsess over every successful payment.</p><div className="mt-5 flex justify-center gap-7 text-sm font-semibold tracking-[-.03em] text-white/35 sm:gap-12"><span>Razorpay</span><span>cashfree</span><span>PhonePe</span><span>UPI</span></div></div>; }
function SignalSection() { return <section id="product" className="grid gap-12 py-24 sm:grid-cols-2 sm:items-center sm:py-36"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-[#b5ff6d]">Your revenue radar</p><h2 className="mt-5 font-display text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">See the moment a payment pattern turns into a problem.</h2><p className="mt-6 max-w-md text-base leading-7 text-white/55">Undrop connects the dots across gateway responses, issuers, payment methods, and customer behavior. You get the context before revenue quietly slips away.</p><ul className="mt-8 space-y-4 text-sm text-white/75">{["Spot unusual failure patterns in real time","Understand which revenue is actually recoverable","Keep a clear audit trail for every decision"].map(t=><li key={t} className="flex gap-3"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#b5ff6d] text-[#11130e]"><Check size={12} weight="bold" /></span>{t}</li>)}</ul></div><motion.div initial={{opacity:0,x:22}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="rounded-[24px] border border-white/[.1] bg-[#10141b] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs text-white/40">Payment signal</p><p className="mt-1 text-lg font-medium">HDFC · UPI Intent</p></div><span className="rounded-full bg-[#ffad70]/10 px-3 py-1.5 text-[11px] text-[#ffb280]">Needs attention</span></div><div className="mt-8 rounded-2xl bg-[#080a0e] p-5"><div className="flex items-end justify-between"><div><p className="text-3xl font-medium tracking-[-.05em]">34.2%</p><p className="mt-1 text-xs text-white/40">Failure rate · last 45 min</p></div><p className="text-xs text-[#ffb280]">↑ 4.3× baseline</p></div><div className="mt-5 h-px bg-white/[.1]" /><div className="mt-4 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#b5ff6d]/10 text-[#b5ff6d]"><Lightning size={17} weight="fill" /></span><p className="text-xs leading-5 text-white/60">Automation switched eligible recoveries to a safer retry window.</p></div></div></motion.div></section>; }
function RecoveryFlow() { const steps=[[ChartLineUp,"Detect","A useful signal, not more noise."],[Lightning,"Decide","The right next step for each payment."],[TrendUp,"Recover","A better moment and method to try again."]]; return <section id="how-it-works" className="rounded-[30px] bg-[#b5ff6d] px-6 py-16 text-[#11130e] sm:px-12 sm:py-20"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#476324]">A closed loop for recovery</p><h2 className="mt-4 font-display text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">Turn every failure into a better next attempt.</h2></div><div className="mt-12 grid gap-8 border-t border-[#11130e]/15 pt-7 sm:grid-cols-3">{steps.map(([Icon,title,body],i)=>{const I=Icon as typeof ChartLineUp;return <div key={title as string}><span className="mb-7 grid h-10 w-10 place-items-center rounded-xl bg-[#11130e] text-[#b5ff6d]"><I size={20} weight="bold" /></span><p className="text-sm font-semibold">0{i+1} · {title as string}</p><p className="mt-2 max-w-[210px] text-sm leading-5 text-[#11130e]/65">{body as string}</p></div>})}</div></section>; }
function Closing() { return <section id="security" className="grid gap-10 py-24 sm:grid-cols-2 sm:items-end sm:py-36"><div><div className="inline-grid h-11 w-11 place-items-center rounded-xl border border-white/[.12] text-[#b5ff6d]"><ShieldCheck size={22} weight="duotone" /></div><h2 className="mt-6 font-display text-4xl font-medium leading-[.98] tracking-[-.055em] sm:text-5xl">Automated with care. Transparent by default.</h2></div><div><p className="max-w-md text-base leading-7 text-white/55">Every action is explainable, every recovery is traceable, and your data stays protected with encryption at rest and in transit.</p><Link href="/sign-up" className="mt-7 inline-block rounded-full border border-white/[.2] px-5 py-3 text-sm font-medium transition hover:border-[#b5ff6d] hover:bg-[#b5ff6d] hover:text-[#11130e]">Meet Undrop <ArrowRight className="ml-1 inline-block" size={16} weight="bold" /></Link></div></section>; }
function Footer() { return <footer className="flex flex-col gap-6 border-t border-white/[.1] py-8 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><Wordmark className="h-6 w-[104px] text-white/80" /><p>© 2026 Undrop. Recovery, with intent.</p><div className="flex gap-5"><a href="#" className="hover:text-white">Privacy</a><a href="#" className="hover:text-white">Terms</a><Link href="/sign-in" className="hover:text-white">Sign in</Link></div></footer>; }
